# MkDocs Configuration for EduPlayKids Documentation
site_name: EduPlayKids - Technical Documentation
site_description: Comprehensive technical documentation for the EduPlayKids educational mobile application
site_author: EduPlayKids Development Team
site_url: https://eduplaykids-docs.github.io/

# Repository information
repo_name: EduPlayKids/EduPlayKids
repo_url: https://github.com/your-org/EduPlayKids
edit_uri: edit/main/docs/

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Technical Documentation:
    - Architecture:
      - Overview: technical/architecture/overview.md
      - Clean Architecture: technical/architecture/clean-architecture.md
      - MVVM Pattern: technical/architecture/mvvm-pattern.md
      - Dependency Injection: technical/architecture/dependency-injection.md
    - Setup & Installation:
      - Development Environment: technical/setup-and-installation/development-environment.md
      - Platform Configuration: technical/setup-and-installation/platform-configuration.md
      - Database Setup: technical/setup-and-installation/database-setup.md
      - Localization: technical/setup-and-installation/localization.md
    - API Documentation:
      - Domain Services: technical/api-documentation/domain-services.md
      - Application Services: technical/api-documentation/application-services.md
      - Data Models: technical/api-documentation/data-models.md
      - Infrastructure APIs: technical/api-documentation/infrastructure-apis.md
    - Development:
      - Coding Standards: technical/development/coding-standards.md
      - XAML Guidelines: technical/development/xaml-guidelines.md
      - Child-Safe Design: technical/development/child-safe-design.md
      - Performance Guidelines: technical/development/performance-guidelines.md
    - Testing:
      - Testing Strategy: technical/testing/testing-strategy.md
      - Unit Testing: technical/testing/unit-testing.md
      - Integration Testing: technical/testing/integration-testing.md
      - UI Testing: technical/testing/ui-testing.md
    - Deployment:
      - Build Process: technical/deployment/build-process.md
      - Release Management: technical/deployment/release-management.md
      - App Store Deployment: technical/deployment/app-store-deployment.md
      - CI/CD Pipeline: technical/deployment/cicd-pipeline.md
    - Performance:
      - Optimization Guidelines: technical/performance/optimization-guidelines.md
      - Memory Management: technical/performance/memory-management.md
      - Battery Optimization: technical/performance/battery-optimization.md
      - Monitoring: technical/performance/monitoring.md
    - Security:
      - Privacy Compliance: technical/security/privacy-compliance.md
      - Child Safety: technical/security/child-safety.md
      - Data Protection: technical/security/data-protection.md
      - Security Best Practices: technical/security/security-best-practices.md
    - Troubleshooting:
      - Common Issues: technical/troubleshooting/common-issues.md
      - Build Problems: technical/troubleshooting/build-problems.md
      - Platform-Specific Issues: technical/troubleshooting/platform-specific-issues.md
      - Performance Issues: technical/troubleshooting/performance-issues.md
  - User Documentation:
    - User Guide: user/user-guide.md
    - Parent Guide: user/parent-guide.md
    - Educational Content: user/educational-content.md
  - Contributing:
    - How to Contribute: contributing/how-to-contribute.md
    - Code of Conduct: contributing/code-of-conduct.md
    - Development Workflow: contributing/development-workflow.md

# Theme configuration
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Table of Contents
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: your-org
      repo: EduPlayKids
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'

# Extra configuration
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/EduPlayKids
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eduplaykids
  generator: false

# Copyright
copyright: |
  Copyright &copy; 2024 EduPlayKids Team. Built for children's education.

# Custom CSS
extra_css:
  - assets/css/custom.css

# Analytics (optional, configure as needed)
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'